#define p0	PINSEL0 
#define p1	PINSEL1 
#define p2	PINSEL2 
#define ddra	IO0DIR 
#define ddrb	IO1DIR 
#define porta	IO0SET 
#define portb	IO1SET 
#define clra	IO0CLR 
#define clrb	IO1CLR 
#define pina	IO0PIN 
#define pinb	IO1PIN 
